### ISSUE TITLE
Make it more obvious the list table is "loading"

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/bulk-user-management#6]
Currently, when the list table is loading users, the table area is whited out a bit and we're using the ajax loading icon from core.

It's not terrible obvious that the ajax loading state is going to result in a list of users being loaded. It might be better to have the ajax loading image front and center with a bit of text that says "Loading users..." or similar.

**Comment by joshbetz** [comment]
@danielbachhuber I was thinking about finding a bigger ajax icon and doing something like this: http://cl.ly/HzKO

Alternatively I could use the same ajax gif from core and do something like this: http://cl.ly/HzFv

I'd like to do something with CSS animation with a fallback for browsers that don't support it, but I'm not sure if it would be possible.

**Comment by danielbachhuber** [comment]
Ooh, I like the second one better. I think it's closer to core UI
